# Generated by Django 5.0.1 on 2024-01-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_description',
            field=models.TextField(null=True),
        ),
    ]
