# Generated by Django 5.0.1 on 2024-01-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_link_portfolio_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_description',
            field=models.TextField(),
        ),
    ]
