# Generated by Django 5.0.1 on 2024-02-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolio_link_alter_portfolio_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='style',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
